<?php

namespace Database\Seeders;

use App\Models\Locations\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $c_ar = [
            "أفغانستان",
            "ألبانيا",
            "الجزائر",
            "ساموا الأمريكية",
            "أندورا",
            "أنغولا",
            "أنغيلا",
            "القارة القطبية الجنوبية",
            "أنتيغوا وبربودا",
            "الأرجنتين",
            "أرمينيا",
            "أروبا",
            "أستراليا",
            "النمسا",
            "أذربيجان",
            "جزر الباهاما",
            "البحرين",
            "بنغلاديش",
            "باربادوس",
            "بيلاروسيا",
            "بلجيكا",
            "بليز",
            "بنين",
            "برمودا",
            "بوتان",
            "بوليفيا",
            "البوسنة والهرسك",
            "بوتسوانا",
            "جزيرة بوفيت",
            "البرازيل",
            "إقليم المحيط الهندي البريطاني",
            "بروناي دار السلام",
            "بلغاريا",
            "بوركينا فاسو",
            "بوروندي",
            "كمبوديا",
            "الكاميرون",
            "كندا",
            "الرأس الأخضر",
            "جزر كايمان",
            "جمهورية إفريقيا الوسطى",
            'تشاد',
            "تشيلي",
            "الصين",
            "جزيرة الكريسماس",
            "جزر كوكس (كيلينغ)",
            "كولومبيا",
            "جزر القمر",
            "جمهورية الكونغو الديمقراطية",
            "جمهورية الكونغو",
            "جزر كوك",
            "كوستاريكا",
            "كرواتيا (هرفاتسكا)",
            "كوبا",
            "قبرص",
            "جمهورية التشيك",
            "الدنمارك",
            "جيبوتي",
            "دومينيكا",
            "جمهورية الدومينيكان",
            "تيمور الشرقية",
            "الإكوادور",
            "مصر",
            "السلفادور",
            "غينيا الاستوائية",
            'إريتريا',
            "إستونيا",
            'إثيوبيا',
            "جزر فوكلاند (مالفيناس)",
            "جزر فارو",
            "فيجي",
            "فنلندا",
            "فرنسا",
            "فرنسا , العاصمة",
            "غيانا الفرنسية",
            "بولينيزيا الفرنسية",
            "الأقاليم الجنوبية الفرنسية",
            "الجابون",
            "غامبيا",
            "جورجيا",
            "ألمانيا",
            "غانا",
            "جبل طارق",
            "غيرنسي",
            "اليونان",
            "جرينلاند",
            "غرينادا",
            "جوادلوب",
            "غوام",
            "جواتيمالا",
            "غينيا",
            "غينيا بيساو",
            "غيانا",
            'هايتي',
            'Heard and Mc Donald Islands',
            "هندوراس",
            "هونج كونج",
            "المجر",
            'أيسلندا',
            "الهند",
            "جزيرة مان",
            "إندونيسيا",
            'جمهورية إيران الإسلامية',
            "العراق",
            "أيرلندا",
            "إسرائيل",
            "إيطاليا",
            "ساحل العاج",
            "جيرسي",
            "جامايكا",
            "اليابان",
            "الأردن",
            "كازاخستان",
            "كينيا",
            "كيريباتي",
            "جمهورية كوريا الديمقراطية الشعبية",
            'جمهورية كوريا',
            "كوسوفو",
            "الكويت",
            "قيرغيزستان",
            "جمهورية لاو الديمقراطية الشعبية",
            "لاتفيا",
            "لبنان",
            "ليسوتو",
            "ليبيريا",
            "الجماهيرية العربية الليبية",
            "ليختنشتاين",
            "ليتوانيا",
            "لوكسمبورغ",
            "ماكاو",
            "مقدونيا الشمالية",
            "مدغشقر",
            "ملاوي",
            "ماليزيا",
            "جزر المالديف",
            "مالي",
            "مالطا",
            "جزر مارشال",
            "مارتينيك",
            "موريتانيا",
            "موريشيوس",
            "مايوت",
            "المكسيك",
            'ولايات ميكرونيزيا الموحدة',
            'جمهورية مولدوفا',
            "موناكو",
            "منغوليا",
            "الجبل الأسود",
            "مونتسيرات",
            "المغرب",
            "موزمبيق",
            "ميانمار",
            "ناميبيا",
            "ناورو",
            "نيبال",
            "هولندا",
            "جزر الأنتيل الهولندية",
            "كاليدونيا الجديدة",
            "نيوزيلندا",
            "نيكاراغوا",
            "النيجر",
            "نيجيريا",
            "نيوي",
            "جزيرة نورفولك",
            "جزر ماريانا الشمالية",
            "النرويج",
            "عمان",
            "باكستان",
            "بالاو",
            'فلسطين',
            "بنما",
            "بابوا غينيا الجديدة",
            "باراغواي",
            "بيرو",
            "الفلبين",
            "بيتكيرن",
            " بولندا",
            "البرتغال",
            "بورتوريكو",
            "قطر",
            "لم الشمل",
            "رومانيا",
            "الاتحاد الروسي",
            "رواندا",
            "سانت كيتس ونيفيس",
            "سانت لوسيا",
            "سانت فنسنت والجرينادينز",
            "ساموا",
            "سان مارينو",
            "ساو تومي وبرينسيبي",
            "المملكة العربية السعودية",
            'السنغال',
            "صربيا",
            "سيشيل",
            "سيراليون",
            "سنغافورة",
            "سلوفاكيا",
            "سلوفينيا",
            "جزر سليمان",
            "الصومال",
            "جنوب إفريقيا",
            "جنوب السودان",
            "جزر ساندويتش الجنوبية الجنوبية بجورجيا الجنوبية",
            "إسبانيا",
            "سريلانكا",
            "سانت. هيلينا",
            'بيير وميكلون',
            "السودان",
            "سورينام",
            "جزر سفالبارد وجان ماين",
            "سوازيلاند",
            "السويد",
            "سويسرا",
            "الجمهورية العربية السورية",
            "تايوان",
            "طاجيكستان",
            'جمهورية تنزانيا المتحدة',
            "تايلاند",
            "توغو",
            "توكيلاو",
            "تونجا",
            "ترينيداد وتوباغو",
            'تونس',
            "تركيا",
            'تركمانستان',
            "جزر تركس وكايكوس",
            "توفالو",
            "أوغندا",
            "أوكرانيا",
            "الإمارات العربية المتحدة",
            "المملكة المتحدة",
            "الولايات المتحدة",
            "جزر الولايات المتحدة الصغيرة النائية",
            "أوروغواي",
            'أوزبكستان',
            "فانواتو",
            "دولة الفاتيكان",
            "فنزويلا",
            "فيتنام",
            "جزر فيرجن (البريطانية)",
            "جزر فيرجن (الولايات المتحدة)",
            "جزر واليس وفوتونا",
            "الصحراء الغربية",
            "اليمن",
            "زامبيا",
            "زيمبابوي"
        ];

        $c_en = array(
            'Afghanistan',
            'Albania',
            'Algeria',
            'American Samoa',
            'Andorra',
            'Angola',
            'Anguilla',
            'Antarctica',
            'Antigua and Barbuda',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bermuda',
            'Bhutan',
            'Bolivia',
            'Bosnia and Herzegovina',
            'Botswana',
            'Bouvet Island',
            'Brazil',
            'British Indian Ocean Territory',
            'Brunei Darussalam',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Cape Verde',
            'Cayman Islands',
            'Central African Republic',
            'Chad',
            'Chile',
            'China',
            'Christmas Island',
            'Cocos (Keeling) Islands',
            'Colombia',
            'Comoros',
            'Democratic Republic of the Congo',
            'Republic of Congo',
            'Cook Islands',
            'Costa Rica',
            'Croatia (Hrvatska)',
            'Cuba',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'East Timor',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Eritrea',
            'Estonia',
            'Ethiopia',
            'Falkland Islands (Malvinas)',
            'Faroe Islands',
            'Fiji',
            'Finland',
            'France',
            'France, Metropolitan',
            'French Guiana',
            'French Polynesia',
            'French Southern Territories',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Gibraltar',
            'Guernsey',
            'Greece',
            'Greenland',
            'Grenada',
            'Guadeloupe',
            'Guam',
            'Guatemala',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Heard and Mc Donald Islands',
            'Honduras',
            'Hong Kong',
            'Hungary',
            'Iceland',
            'India',
            'Isle of Man',
            'Indonesia',
            'Iran (Islamic Republic of)',
            'Iraq',
            'Ireland',
            'Israel',
            'Italy',
            'Ivory Coast',
            'Jersey',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea, Democratic People\'s Republic of',
            'Korea, Republic of',
            'Kosovo',
            'Kuwait',
            'Kyrgyzstan',
            'Lao People\'s Democratic Republic',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libyan Arab Jamahiriya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Macau',
            'North Macedonia',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Islands',
            'Martinique',
            'Mauritania',
            'Mauritius',
            'Mayotte',
            'Mexico',
            'Micronesia, Federated States of',
            'Moldova, Republic of',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Montserrat',
            'Morocco',
            'Mozambique',
            'Myanmar',
            'Namibia',
            'Nauru',
            'Nepal',
            'Netherlands',
            'Netherlands Antilles',
            'New Caledonia',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Niue',
            'Norfolk Island',
            'Northern Mariana Islands',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Palestine',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Pitcairn',
            'Poland',
            'Portugal',
            'Puerto Rico',
            'Qatar',
            'Reunion',
            'Romania',
            'Russian Federation',
            'Rwanda',
            'Saint Kitts and Nevis',
            'Saint Lucia',
            'Saint Vincent and the Grenadines',
            'Samoa',
            'San Marino',
            'Sao Tome and Principe',
            'Saudi Arabia',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Slovakia',
            'Slovenia',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Sudan',
            'South Georgia South Sandwich Islands',
            'Spain',
            'Sri Lanka',
            'St. Helena',
            'St. Pierre and Miquelon',
            'Sudan',
            'Suriname',
            'Svalbard and Jan Mayen Islands',
            'Swaziland',
            'Sweden',
            'Switzerland',
            'Syrian Arab Republic',
            'Taiwan',
            'Tajikistan',
            'Tanzania, United Republic of',
            'Thailand',
            'Togo',
            'Tokelau',
            'Tonga',
            'Trinidad and Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Turks and Caicos Islands',
            'Tuvalu',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'United States',
            'United States minor outlying islands',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Vatican City State',
            'Venezuela',
            'Vietnam',
            'Virgin Islands (British)',
            'Virgin Islands (U.S.)',
            'Wallis and Futuna Islands',
            'Western Sahara',
            'Yemen',
            'Zambia',
            'Zimbabwe'
        );

        $countries = [];

        for ($i = 0; $i < count($c_ar); $i++) {
            $countries[$i]['name']['ar'] = $c_ar[$i];
            $countries[$i]['name']['en'] = $c_en[$i];
            $countries[$i]['status'] = 'inactive';
        }


        foreach ($countries as $country) {

            Country::create([
                'name' => json_encode($country['name']),
            ]);
        }

    }
}
